<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INBLRNB0299" ignored="1" name="testcase1" tests="6" failures="1" timestamp="31 Mar 2019 09:43:40 GMT" time="1.06" errors="0">
  <testcase name="f1" time="0.016" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f2" time="0.0" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f3" time="0.0" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f4" time="0.0" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f6" time="0.0" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f7" time="1.007" classname="testngsnippet.TestNgTestCase1">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngsnippet.TestNgTestCase1.f7() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngsnippet.TestNgTestCase1.f7() didn't finish within the time-out 1000
at java.util.concurrent.ThreadPoolExecutor.afterExecute(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- f7 -->
  <testcase name="f5" time="0.0" classname="testngsnippet.TestNgTestCase1">
    <ignored/>
  </testcase> <!-- f5 -->
</testsuite> <!-- testcase1 -->
